<?xml version="1.0" encoding="UTF-8" standalone='yes'?>
	
<!-- 
Aos configuration 

To edit: Notepad.OpenAscii AosConfig.XML
To update: AosConfig.Init ~
-->
	<!DOCTYPE Config [
		<!ELEMENT Section ANY>
		<!ATTLIST Section
			name NMTOKEN #REQUIRED
			>
		<!ELEMENT Setting ANY>
		<!ATTLIST Setting
			name NMTOKEN #IMPLIED
			value CDATA #REQUIRED
			>
		]>
	<Config>
	<!-- Localization -->
		
		<Section name="Local">
			<Section name="Formats">
				<Section name="Date">
					<Setting name="Short" value="dd.mm.yy"/>
					<Setting name="Long" value="www, dd.mm.yyyy"/>
				</Section>
				<Section name="Time">
					<Setting name="Short" value="hh:nn"/>
					<Setting name="Long" value="hh:nn:ss"/>
				</Section>
				<Section name="Timezone">
					<Setting name="Name" value="GMT-1"/>
					<Setting name="GMTDiff" value="+1"/>
				</Section>
			</Section>
		</Section>
		
	<!-- File systems -->
		
		<Section name="AosFS">
			<Section name="Alias">
				<Setting name="AosFS" value="AosDiskVolumes.New;AosDiskFS.NewFS"/>
				<Setting name="NatFS" value="AosDiskVolumes.New;AosDiskFS.NewFS"/>
				<Setting name="RamFS" value="AosRAMVolumes.New;AosDiskFS.NewFS"/>
				<Setting name="FatFS" value="AosFATVolumes.New;AosFATFiles.NewFS"/>
				<Setting name="IsoFS" value="AosISO9660Volumes.New;AosISO9660Files.NewFS"/>
				<Setting name="ZipFS" value="NIL;AosZipFS.NewFS"/>
				<Setting name="WinRelFS" value="NIL;Win32RelFS.NewFS"/>
			</Section>
		</Section>
		
	<!-- Autostart -->
		
		<Section name="Autostart">
			<Setting name="Uptime Monitor" value="UpTime.Install"/>
			<Setting name="Start the main menu" value="StartMenu.Open"/>
			<Setting name="Restore the desktop" value="WMRestorable.Load Auto.dsk"/>
			
		<!-- Pinyin Input Method Editor (remove comment to activate)
			<Setting value="WMPinyinIME.Test"/>
		-->
			
			
		<!-- Quote Server (remove comment to activate)
			<Setting value="AosQuoteServer.Open"/>
		-->
			
			<Setting name="DefaultSkin" value="SkinEngine.Load stijn.skin"/>
			
		<!--Setting name="Hotkey support" value="AosHotKeys.Open"/-->
			
			
		<!--Setting name="Hardware Detection" value="AosPCITools.DetectHardware"/-->
			
			<Setting name="TrapWriter" value="WMTrapWriter.Install"/>
		</Section>
		
	<!-- WindowManager -->
		
		<Section name="WindowManager">
			<Section name="FontManager">
				<Section name="DefaultFont">
					<Setting name="Name" value="Oberon"/>
					<Setting name="Size" value="12"/>
				</Section>
				<Section name="FontLoaders">
					<Section name="OberonFonts">
						<Setting name="Exact" value="WMOberonFonts.LoadExactFont"/>
						<Setting name="Approximate" value="WMOberonFonts.LoadApproximateFont"/>
					</Section>
					<Section name="BitmapFonts">
						<Setting name="Exact" value="WMBitmapFont.LoadExactFont"/>
						<Setting name="Approximate" value="WMBitmapFont.LoadApproximateFont"/>
					</Section>
					<Section name="CCGFonts">
						<Setting name="Exact" value="WMCCGFonts.LoadExactFont"/>
						<Setting name="Approximate" value="WMCCGFonts.LoadApproximateFont"/>
					</Section>
					<Section name="OTFonts">
						<Setting name="Exact" value="WMOTFonts.LoadExactFont"/>
						<Setting name="Approximate" value="WMOTFonts.LoadApproximateFont"/>
					</Section>
				</Section>
				
			<!-- FOR COMPATIBILTY. TO BE REMOVED (staubesv) -->
				
				<Section name="OberonFonts">
					<Setting name="Exact" value="WMOberonFonts.LoadExactFont"/>
					<Setting name="Approximate" value="WMOberonFonts.LoadApproximateFont"/>
				</Section>
				<Section name="BitmapFonts">
					<Setting name="Exact" value="WMBitmapFont.LoadExactFont"/>
					<Setting name="Approximate" value="WMBitmapFont.LoadApproximateFont"/>
				</Section>
				<Section name="CCGFonts">
					<Setting name="Exact" value="WMCCGFonts.LoadExactFont"/>
					<Setting name="Approximate" value="WMCCGFonts.LoadApproximateFont"/>
				</Section>
				<Section name="OTFonts">
					<Setting name="Exact" value="WMOTFonts.LoadExactFont"/>
					<Setting name="Approximate" value="WMOTFonts.LoadApproximateFont"/>
				</Section>
			</Section>
		</Section>
		
	<!-- Font formats for AosGfxFonts.Open -->
		
		<Section name="FontFormats">
			<Setting name="TTF" value="AosGfxOType.Install"/>
			<Setting name="pk" value="AosGfxPKFonts.Install"/>
		</Section>
		
	<!-- TLS Settings -->
		
		<Section name="TLS">
			<Setting name="Certificate" value="bluebottleselfsigned.der"/>
			<Setting name="pHex" value="00fbe3108714d0f161c79b2fd03eaf8be07b477fbd534a1059d7244513b075700ec6d00cd6c61445932f6439ed31050e6ad43a51f1692e51e3e4691cab3d230ba7"/>
			<Setting name="qHex" value="00e7e7a06664c5a91c0502a010e2efffdbddf2fb6cbac07116e63c4b2090d1bd1ef1db15619a73cd34a490df9c1c86259bfa2bf71aab5e4f5414d4b9cc2f777d0d"/>
			<Setting name="eHex" value="10001"/>
			<Setting name="pLen" value="130"/>
			<Setting name="qLen" value="130"/>
			<Setting name="eLen" value="5"/>
		</Section>
		<Section name="Archives">
			<Setting name="tar" value="AosTar"/>
			<Setting name="skin" value="AosTar"/>
		</Section>
		
	<!-- Codecs -->
		
		<Section name="Codecs">
		<!-- Multiplexer -->
			
			<Section name="Multiplexer"/>
			
		<!-- Demultiplexer -->
			
			<Section name="Demultiplexer">
				<Setting name="AVI" value="AVI.Factory"/>
				<Setting name="MPG" value="MPEGVideoDecoder.DemuxFactory"/>
			</Section>
			
		<!-- Encoders -->
			
			<Section name="Encoder">
				<Section name="Text">
					<Setting name="Oberon" value="AosTextUtilities.OberonEncoderFactory"/>
					<Setting name="BBT" value="AosTextUtilities.BluebottleEncoderFactory"/>
					<Setting name="UTF-8" value="AosTextUtilities.UTF8EncoderFactory"/>
					<Setting name="ISO8859-1" value="AosTextUtilities.ISO88591EncoderFactory"/>
					<Setting name="HEX" value="AosTextUtilities.HEXEncoderFactory"/>
				</Section>
				<Section name="Image">
					<Setting name="BMP" value="AosBMPCodec.EncoderFactory"/>
					<Setting name="GIF" value="AosGIFCodec.EncoderFactory"/>
				</Section>
				<Section name="Video"/>
				<Section name="Audio">
					<Setting name="WAV" value="AosWAVCodec.EncoderFactory"/>
				</Section>
			</Section>
			
		<!-- Decoders -->
			
			<Section name="Decoder">
				<Section name="Text">
					<Setting name="Oberon" value="AosTextUtilities.OberonDecoderFactory"/>
					<Setting name="BBT" value="AosTextUtilities.BluebottleDecoderFactory"/>
					<Setting name="UTF-8" value="AosTextUtilities.UTF8DecoderFactory"/>
					<Setting name="ISO8859-1" value="AosTextUtilities.ISO88591DecoderFactory"/>
					<Setting name="HEX" value="AosTextUtilities.HEXDecoderFactory"/>
				</Section>
				<Section name="Image">
					<Setting name="JP2" value="JPEG2000Decoder.Factory"/>
					<Setting name="PNG" value="AosPNGDecoder.Factory"/>
					<Setting name="BMP" value="AosBMPCodec.DecoderFactory"/>
					<Setting name="GIF" value="AosGIFCodec.DecoderFactory"/>
					<Setting name="JPEG" value="AosJPEGDecoder.Factory"/>
					<Setting name="JPG" value="AosJPEGDecoder.Factory"/>
					<Setting name="SVG" value="SVGDecoder.Factory"/>
				</Section>
				<Section name="Video">
					<Setting name="DivX" value="AosDivXDecoder.Factory"/>
					<Setting name="DIVX" value="AosDivXDecoder.Factory"/>
					<Setting name="divx" value="AosDivXDecoder.Factory"/>
					<Setting name="MPG" value="MPEGVideoDecoder.DecoderFactory"/>
				</Section>
				<Section name="Audio">
					<Setting name="MP3" value="AosMP3Decoder.Factory"/>
					<Setting name="WAV" value="AosWAVCodec.DecoderFactory"/>
				</Section>
			</Section>
		</Section>
		
	<!-- Filehandlers-->
		
		<Section name="Filehandlers">
		<!-- use lower case for extensions, sort lexographically -->
			
			<Setting name="asm" value="PET.Open"/>
			<Setting name="avi" value="WMPlayer.Open"/>
			<Setting name="bak" value="PET.Open"/>
			<Setting name="bmp" value="WMPicView.Open"/>
			<Setting name="gif" value="WMPicView.Open"/>
			<Setting name="htm" value="WebBrowser.OpenFile"/>
			<Setting name="html" value="WebBrowser.OpenFile"/>
			<Setting name="jp2" value="WMPicView.Open"/>
			<Setting name="jpeg" value="WMPicView.Open"/>
			<Setting name="jpg" value="WMPicView.Open"/>
			<Setting name="log" value="PET.Open"/>
			<Setting name="mod" value="PET.Open"/>
			<Setting name="mp3" value="WMPlayer.Open"/>
			<Setting name="abx" value="AosDecoder.Open"/>
			<Setting name="oba" value="AosDecoder.Open"/>
			<Setting name="obx" value="AosDecoder.Open"/>
			<Setting name="obw" value="AosDecoder.Open"/>
			<Setting name="ogg" value="OGGVorbisPlayer.Play"/>
			<Setting name="pet" value="PET.OpenState"/>
			<Setting name="pict" value="WMPicView.Open"/>
			<Setting name="png" value="WMPicView.Open"/>
			<Setting name="skin" value="SkinEditor.OpenSkin"/>
			<Setting name="svg" value="WebBrowser.OpenFile"/>
			<Setting name="tar" value="WMArchives.Open"/>
			<Setting name="text" value="Notepad.OpenAuto"/>
			<Setting name="txt" value="Notepad.OpenAuto"/>
			<Setting name="tool" value="PET.Open"/>
			<Setting name="wav" value="WMPlayer.Open"/>
			<Setting name="xml" value="PET.Open"/>
		</Section>
		
	<!-- Net Configuration Example -->
		
		
	<!--Section name="NetConfig">
		<Setting name="IPForwarding" value="FALSE" />
		<Setting name="EchoReply" value="TRUE" />
		<Setting name="PreferredProtocol" value="4" />
	
		<Section name="IPv4">
			<Section name="AutoNetConfig">
				<Setting name="Enabled" value="TRUE" />
			</Section>
	
			<Section name="Interface">
				<Setting name="Device" value="RTL8139#0" />
				<Setting name="Name" value="localv4" />
				<Setting name="Domain" value="mydomain.com" />
				<Setting name="DHCP" value="FALSE" />
				<Setting name="LocalAdr" value="192.168.1.17" />
				<Setting name="Gateway" value="192.168.1.1" />
				<Setting name="Netmask" value="255.255.255.0" />
				<Setting name="DNS" value="192.168.1.1" />
			</Section>
			
			<Section name="Interface">
				<Setting name="Device" value="RTL8139#0" />
				<Setting name="Name" value="dhcp" />
				<Setting name="Domain" value="mydomain.com" />
				<Setting name="DHCP" value="TRUE" />
			</Section>
		</Section>
	
		<Section name="IPv6">
			<Section name="AutoNetConfig">
				<Setting name="Enabled" value="TRUE" />
				<Setting name="DNS" value="2001::1" />
			</Section>
			
			<Section name="Interface">
				<Setting name="Device" value="RTL8139#0" />
				<Setting name="Name" value="v6Static" />
				<Setting name="DHCP" value="FALSE" />
				<Setting name="LocalAdr" value="2001:db8::1234:abcd" />
				<Setting name="Prefix" value="2001:db8::/32" />
				<Setting name="DNS" value="2001::1" />
			</Section>
		</Section>
	</Section -->
		
		
	<!-- Applications -->
		
		<Section name="Applications">

			<Section name="PET">
				<Section name="General">
					<Setting name="ParanoidBackups" value="TRUE"/>
					<Setting name="BackupOnCompile" value="FALSE"/>
					<Setting name="ShowPathInTabs" value="FALSE"/>
					<Setting name="ScratchPanelHeight" value="250"/>
					<Setting name="EnableWhitespaceWarnings" value="FALSE"/>
				</Section>
				<Section name="Compilers">
					<Setting name="PACO" caption="Compile" options="\Ws" fileExtension="MOD" loadmodule="PC0" tree="TRUE" findPC="TRUE"/>
					<Setting name="ReleaseTool" caption="Parse" options="\check" fileExtension="Tool" loadmodule="AosRelease" tree="FALSE" findPC="FALSE"/>
					<Setting name="AAMD64" caption="Assemble" options="" fileExtension="ASM" loadmodule="PCAAMD64" tree="FALSE" findPC="FALSE"/>
				</Section>
				<Section name="Diff">
					<Setting name="Command" value="WMDiff.Open"/>
					<Setting name="Prefix" value=""/>
					<Setting name="Suffix" value=".Bak"/>
				</Section>
				<Section name="Search">
					<Setting name="Wrap" value="FALSE"/>
					<Setting name="HighlightAll" value="FALSE"/>
					<Setting name="CaseSensitive" value="TRUE"/>
				</Section>
			</Section>

			<Section name="WMV24Component">
				<Setting name="WindowStartupSize" value="800x400"/>
				<Setting name="IndicateKeyboardFocus" value="TRUE"/>
				<Setting name="LineFeed" value="FALSE"/>
				<Setting name="UseBackspace" value="TRUE"/>
				<Setting name="ShowStatusBar" value="TRUE"/>
				<Setting name="Echo" value="FALSE"/>
				
			<!-- PortNumber Bps Databits Stopbits Parity -->
				
				<Setting name="PortSettings" value="1 115200 8 1 none"/>
				
			<!-- When pressing X/Y-Send buttons, the optional command string is sent to the target device (incl. CR) before sending -->
				
				<Setting name="XReceiveCommand" value=""/>
				<Setting name="YReceiveCommand" value=""/>
				
			<!-- When pressing X/Y-Receive buttons, the optional command string and the filename is sent to the target device -->
				
				<Setting name="XSendCommand" value=""/>
				<Setting name="YSendCommand" value=""/>
				
			<!-- User-defined commands for the command menu -->
				
				<Section name="CommandMenu">
					<Setting name="Command1" value=""/>
					<Setting name="Command2" value=""/>
				</Section>
			</Section>
			
		<!-- Standard Settings for the IMAP/SMTP Client -->
			
			<Section name="MailClient">
				<Setting name="IMAPServer" value=""/>
				<Setting name="UserName" value=""/>
				<Setting name="SMTPServer" value=""/>
				<Setting name="SMTPThisHost" value=""/>
				<Setting name="ExpungeOnFolderChange" value="TRUE"/>
				<Setting name="ExpungeOnDelete" value="FALSE"/>
				<Setting name="UseDragNDropAsMove" value="TRUE"/>
				<Setting name="ExpungeOnMove" value="TRUE"/>
				<Setting name="UseATrashBin" value="FALSE"/>
				<Setting name="SentFolder" value=""/>
				<Setting name="DraftFolder" value=""/>
				<Setting name="TrashBin" value=""/>
				<Setting name="From" value=""/>
			</Section>
			<Section name="Performance Monitor">
				<Section name="Plugins">
				<!-- Specify which plugins should be loaded at startup -->
					
					<Setting name="WMPerfMonPluginCpu" value="TRUE"/>
					<Setting name="WMPerfMonPluginMemory" value="TRUE"/>
					<Setting name="WMPerfMonPluginPerfMon" value="TRUE"/>
					<Setting name="WMPerfMonPluginMessages" value="TRUE"/>
					<Setting name="WMPerfMonPluginNetStats" value="FALSE"/>
					<Setting name="WMPerfMonPluginEvents" value="TRUE"/>
					
				<!-- kernel statistics plugins -->
					
					<Setting name="WMPerfMonPluginActive" value="FALSE"/>
					<Setting name="WMPerfMonPluginHeap" value="FALSE"/>
					
				<!-- device performance plugins -->
					
					<Setting name="WMPerfMonPluginNetwork" value="TRUE"/>
					<Setting name="WMPerfMonPluginSerials" value="FALSE"/>
					<Setting name="WMPerfMonPluginDisks" value="TRUE"/>
					<Setting name="WMPerfMonPluginUsb" value="TRUE"/>
					
				<!-- server statistics plugins -->
					
					<Setting name="WMPerfMonPluginHTTPServer" value="FALSE"/>
					<Setting name="WMPerfMonPluginFTPServer" value="FALSE"/>
					<Setting name="WMPerfMonPluginVNCServer" value="FALSE"/>
					<Setting name="WMPerfMonPluginQuoteServer" value="FALSE"/>
					
				<!-- other plugins -->
					
					<Setting name="WMPerfMonPluginExample" value="FALSE"/>
				</Section>
			</Section>
		</Section>
		
	<!-- Paco Compiler -->
		
		<Section name="Paco">
			<Setting name="ErrorMessages" value="Errors.XML"/>
		</Section>
		
	<!-- Example of nested sections -->
		
		<Section name="A">
			<Section name="B">
				<Section name="C">
					<Setting name="D" value="Hello world"/>
				</Section>
			</Section>
		</Section>
	</Config>